### ISSUE TITLE
About the object categories

### ISSUE THREAD

**Issue by LynnCtt** [xdshang/VidVRD-helper#1]
Hello, I'm Tingting. Now I'm trying to use your dataset and extra annotations to train my model. But I found that ball,sofa,person are not include in 30 basic-level categories and frisbee, skateboard are not include in 200 basic-level categories. How can I add them,especially frisbee and skateboard,  into  categories of detect object from video?

**Comment by JellyWong** [comment]
Actually, you could find frisbee, skateboard and person in the MS-COCO. According to the paper, you are expected to collect all your categories in the union set of MS-COCO and ILSVRC2016-DET.
