### ISSUE TITLE
Where to download videos and annotations

### ISSUE THREAD

**Issue by gurkirt** [xdshang/VidVRD-helper#11]
Thank you very much for releasing the dataset.

Where can I download videos and annotations?

**Comment by gurkirt** [comment]
I found the videos at http://dl.nextcenter.org/public/vidvrd/vidvrd-videos.zip
But, still can not find the annotations

**Comment by gurkirt** [comment]
@xdshang please help with the annotation file

**Comment by xdshang** [comment]
@gurkirt please find the annotations in the dataset page (https://lms.comp.nus.edu.sg/research/VidVRD.html).

**Comment by gurkirt** [comment]
Thanks a lot :)
