### ISSUE TITLE
Ground file genration 

### ISSUE THREAD

**Issue by gurkirt** [xdshang/VidVRD-helper#12]
I was looking at the evaluation protocol in https://github.com/xdshang/VidVRD-helper/blob/master/evaluation/visual_relation_detection.py

It Looks very clean and readable. However, I noticed that the ground truth file is a single json file created by merging ground truth json files of each video.
https://github.com/xdshang/VidVRD-helper/blob/master/evaluation/visual_relation_detection.py#L129

It says there that 'A ground truth JSON file generated by yourself'

How to create this ground truth file and detection file.

**Comment by xdshang** [comment]
It is recommended to run the `evaluate.py` in the root directory as follows, which will directly load the ground truth from the downloaded dataset.
```
python evaluate.py [dataset_name] [split_name] [task_name] [path_to_prediction_json]
```

If you want to run the `evaluation/visual_relation_detection.py` individually, then you need to generate a single ground truth JSON file yourself using the dataset script `dataset/vidvrd.py`. However, the script currently doesn't support such function as that in `dataset/vidor.py`. I will update it later.

**Comment by xdshang** [comment]
@gurkirt `dataset/vidvrd.py` updated.

**Comment by gurkirt** [comment]
Great! Thanks!
