### ISSUE TITLE
Link for features, model and relations is not working

### ISSUE THREAD

**Issue by nirat1606** [xdshang/VidVRD-helper#13]
Hi @xdshang, 

The link given for baseline code dataset precomputed features, model and detected relations [here](https://lms.comp.nus.edu.sg/research/public_data/vidvrd/vidvrd-baseline-output.zip) seems to be dead, could you please update it or point me to the correct link?

Thanks,
Nirat

**Comment by xdshang** [comment]
Hi Nirat, please see the updated links. Should work now :smiley:

**Comment by nirat1606** [comment]
Thank you @xdshang :)
