### ISSUE TITLE
Baseline pretrained models Link 1 is invalid.

### ISSUE THREAD

**Issue by Heliang-Zheng** [xdshang/VidVRD-helper#15]
The Link 1 in Baseline folder https://lms.comp.nus.edu.sg/research/public_data/vidvrd/vidvrd-baseline-output.zip is invalid, could you pls check?

**Comment by xdshang** [comment]
@Heliang-Zheng Link 1 is temporarily unavailable, please use Link 2 to download.

**Comment by Heliang-Zheng** [comment]
Thanks!
