### ISSUE TITLE
Problems about class DataGenerator and function extract_feature

### ISSUE THREAD

**Issue by Dawn-LX** [xdshang/VidVRD-helper#16]
What is the meaning of `dry_run` and `verbose` in function `self.extract_feature` at  https://github.com/xdshang/VidVRD-helper/blob/25dca4efeb1eee7ca1415058715ce633b4385dd6/baseline/feature.py#L118

I will be appreciate it that if you can answer my question

**Comment by xdshang** [comment]
These are deprecated arguments, please ignore them :)

**Comment by Dawn-LX** [comment]
> These are deprecated arguments, please ignore them :)

Thank you! 
Is this means that I can just treat `dry_run` and `verbose` as `False` when using  `extract_feature` ? 
Besides, In some places at `class DataGenerator(FeatureExtractor)` in https://github.com/xdshang/VidVRD-helper/blob/master/baseline/model.py, there are some lines like `if self.extract_feature(vid, fstart, fend, dry_run=True)`. 
Is that means I can just replace these lines as `if True:` ?

**Comment by xdshang** [comment]
Sorry for the late reply. When `dry_run=True`, calling `extract_feature` is just for making sure the feature file existing. So you can absolutely use other smarter way to replace this implementation.

**Comment by Dawn-LX** [comment]
> Sorry for the late reply. When `dry_run=True`, calling `extract_feature` is just for making sure the feature file existing. So you can absolutely use other smarter way to replace this implementation.

Thank you very much! It's very helpful!
