### ISSUE TITLE
How to extract features?

### ISSUE THREAD

**Issue by LiaoYqqq** [xdshang/VidVRD-helper#17]
Hi, Thanking you for sharing the code and datasets.
The features of the video( bounding box trajectories, object feature, relation feature, and so on) have been provided but there is no code about the process to extract these features.
I want to know how to extract these features.  Can the code for feature extraction be open source? Thank you!

**Comment by xdshang** [comment]
Hi, the process to extract the features is as described in this [paper](https://dl.acm.org/doi/10.1145/3123266.3123380). The code of this part has many deprecated dependencies so is difficult to be open source.

If you are looking for some precomputed feature for the VidOR dataset, you can find it in this  [link](https://videorelation.nextcenter.org/mm20-gdc/task1.html).

**Comment by LiaoYqqq** [comment]
Thanks！

**Comment by LiaoYqqq** [comment]
Hi, I just find that Link1 and Link2 on this video relation understanding website are unavailable for me. 
When I click it, It shows "This XML file does not appear to have any style information associated with it. <Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist.</Message>
</Error>"

**Comment by xdshang** [comment]
> Hi, I just find that Link1 and Link2 on this video relation understanding website are unavailable for me.
> When I click it, It shows "This XML file does not appear to have any style information associated with it. 
> `NoSuchBucket`
> The specified bucket does not exist.
> "

Please try this new [link](https://zdtnag7mmr.larksuite.com/file/boxusugavBW2RyKEE277UdPROyb).

**Comment by ZYao720** [comment]
@xdshang could you also provide some precomputed feature for the VidVRD dataset?

**Comment by ZYao720** [comment]
@xdshang Hi, thank you for sharing the datasets. I downloaded vidvrd_baseline_output  and I'm trying to understand the content. Could you correct me if I'm wrong?
All files from the folder `traj_cls` are actually the output of the object tracking model.
.h5 files from the folder `relation` contains `feats` (shoud be iDT features), `pairs` (trackid of sub and obj?), `trackid`(id of relation?), and `iou` (have no idea). 
If possible, could you explain it in more detail? Thanks in advance!

**Comment by xdshang** [comment]
Hi @ZYao720 , please refer to the corresponding comments [here](https://github.com/xdshang/VidVRD-helper/blob/25dca4efeb1eee7ca1415058715ce633b4385dd6/baseline/feature.py#L128). For `feats`, it also include classeme and positional features as detailed [here](https://github.com/xdshang/VidVRD-helper/blob/25dca4efeb1eee7ca1415058715ce633b4385dd6/baseline/model.py#L27).
