### ISSUE TITLE
The link for precomputed features, model and detected relations is not available

### ISSUE THREAD

**Issue by cecilia930426** [xdshang/VidVRD-helper#18]
The link for precomputed features, model and detected relations is not available. Could you please provide a new link. Thanks.

**Comment by xdshang** [comment]
Hi, the link works at my side. Are you using [this link](https://zdtnag7mmr.larksuite.com/file/boxusS8Z0kwEizoPPh5h7vx7Usf)?

**Comment by cecilia930426** [comment]
> Hi, the link works at my side. Are you using [this link](https://zdtnag7mmr.larksuite.com/file/boxusS8Z0kwEizoPPh5h7vx7Usf)?

Yes. It cannot be downloaded and stopped many times. Many friends help me to download it, but we all get the same issues. Could you provide another place to download it? Thanks a lot.

**Comment by xdshang** [comment]
Please try this Baidu Pan link then:
链接: https://pan.baidu.com/s/1SsN6iSkRjuwa-TLM6aByBQ
提取码: ambz

**Comment by xdshang** [comment]
> > Hi, the link works at my side. Are you using [this link](https://zdtnag7mmr.larksuite.com/file/boxusS8Z0kwEizoPPh5h7vx7Usf)?
> 
> Yes. It cannot be downloaded and stopped many times. Many friends help me to download it, but we all get the same issues. Could you provide another place to download it? Thanks a lot.

Please try this Baidu Pan link then:
链接: https://pan.baidu.com/s/1SsN6iSkRjuwa-TLM6aByBQ
提取码: ambz
