### ISSUE TITLE
The link for annotations is not available

### ISSUE THREAD

**Issue by Retickence** [xdshang/VidVRD-helper#22]
There are no annotations in the link(https://pan.baidu.com/s/1HyrZ-8AxObtlT8tBKjkcBA?pwd=p9g5). Could you please provide a new link. Thanks.

**Comment by xdshang** [comment]
Hi @Retickence , thanks for letting me know the issue. Please try this revised [link](https://pan.baidu.com/s/1EFXAP-p_qlG0wBCaVLxE1A?pwd=k638), and the website is updated accordingly as well.

**Comment by Retickence** [comment]
Hi @xdshang, the new link is available. Thanks a lot.
