### ISSUE TITLE
Could you maybe provide us a prediction.json sample file for us to directly check how the evaluation metric works?

### ISSUE THREAD

**Issue by LilyDaytoy** [xdshang/VidVRD-helper#23]
Hi! Thanks for the great work!
We would like to understand more about how evaluation metric works for VidSGG task by directly looking at your evaluation codes.

May I ask if you could provide a prediction.json for `relation` task sample file, so that we can directly run the `visual_relation_detection.py ` ?
Thanks a lot! :D

**Comment by xdshang** [comment]
Hi! You may have a look at baseline/README.md. Some precomputed result is available [here](https://zdtnag7mmr.larksuite.com/file/boxusS8Z0kwEizoPPh5h7vx7Usf).
