### ISSUE TITLE
Convert object annotation to yolo

### ISSUE THREAD

**Issue by b3r-prog** [xdshang/VidVRD-helper#24]
@xdshang any idea on how to convert the object task to yolo format?

**Comment by xdshang** [comment]
> @xdshang any idea on how to convert the object task to yolo format?

@b3r-prog Haven't done this before. You may have a look at this post: https://stackoverflow.com/questions/56115874/how-to-convert-bounding-box-x1-y1-x2-y2-to-yolo-style-x-y-w-h
