### ISSUE TITLE
vidvrd下载链接失效了

### ISSUE THREAD

**Issue by fzupang** [xdshang/VidVRD-helper#9]
你好，我想下载vidvrd数据集，但其中videos的链接失效了，请问还有其他的下载方式吗

**Comment by xdshang** [comment]
请确认下是否是用以下这个链接下载的，这个链接目前测试还是有效的。
http://dl.nextcenter.org/public/vidvrd/vidvrd-videos.zip

**Comment by fzupang** [comment]
> 请确认下是否是用以下这个链接下载的，这个链接目前测试还是有效的。
> http://dl.nextcenter.org/public/vidvrd/vidvrd-videos.zip

感谢！！我之前弄错了，用的是这个链接里的
http://lms.comp.nus.edu.sg/research/VidVRD.html

**Comment by fzupang** [comment]
打扰了~还想问个问题，dataset.py是不是还没有更新，里面只有dataset类，没有baseline.py里import的vidVRD

**Comment by xdshang** [comment]
VidVRD这个类在`dataset/vidvrd.py`里
